contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://dumbfunded.io/"
languageCode = "en-us"
title = "dumbfunded"
paginate = 5
theme = "dumbfunded"
googleAnalytics = "UA-76063110-1"

[params]
  description = "mocking the futility of (startup) life"
  logo = "https://d2sf4lafib8dnc.cloudfront.net/dumbfunded.svg"
  og = "https://dumbfunded.imgix.net/dumbfunded_small.pdf?auto=format&fm=png&w=640"

[taxonomies]
  tag = "tags"
  category = "categories"
