contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "/"
languageCode = "en-us"
title = "dumbfunded"
paginate = 5
theme = "dumbfunded"
googleAnalytics = "UA-76063110-1"

[params]
  description = "mocking the futility of (startup) life"
  cover = "https://dumbfunded.imgix.net/dumbfunded_large.svg"

[taxonomies]
  tag = "tags"
  category = "categories"

